### Prueba del microsevicio
GET http://127.0.0.1:8000/
Content-Type: text/html

### Crear un nuevo registro
POST http://127.0.0.1:8000/api/ingresos
Content-Type: application/json"
{
  "codigoEstudiante": "123456",
  "nombreEstudiante": "Juan Perez",
  "idPrograma": 1,
  "fechaIngreso": "2024-05-29",
  "horaIngreso": "08:00",
  "idResponsable": 2,
  "idSala": 3
}

### Actualizar un registro
PUT http://127.0.0.1:8000/api/ingresos
Content-Type: application/json
{
  "codigoEstudiante": "654321",
  "nombreEstudiante": "Maria Lopez",
  "horaSalida": "10:00"
}

### Eliminar un registro
DELETE http://127.0.0.1:8000/api/ingresos/1

### Consultar Ingresos en un Rango de Fechas
GET http://127.0.0.1:8000/api/ingresos
Content-Type: application/json
{
  "startDate": "2024-05-01",
  "endDate": "2024-05-29"
}'

### Filtrar Ingresos
GET http://127.0.0.1:8000/api/ingresos
Content-Type: application/json
{
  "codigoEstudiante": "123456",
  "idPrograma": 1,
  "idResponsable": 2
}'

